### ISSUE TITLE
Session Averages do not compute

### ISSUE THREAD

**Issue by JollyRgrs** [ubelhj/OBSCounter#4]
I am not sure when it started (just within the last few months) Session Averages are broken for me. It just shows "0.0".
I've even reset Bakkesmod and installed again with no change. I did this for demos/goals/assists and all have the same issue with Session Averages. Both the game counter and the session totals work, but the average never changes from all zeros.

**Comment by ubelhj** [comment]
Oh man I fixed this and must have forgotten to upload to bakkesplugins! I changed some logic to try and reduce impact on the game and due to some bad function naming I ended up breaking some functionality I didn't expect to. Turn on writing stats to files for a temporary fix before the new version is uploaded.

**Comment by JollyRgrs** [comment]
Can confirm, temporary solution working great, thanks for the tip.

**Comment by ubelhj** [comment]
Newest version on bakkesplugins.com should solve the issue. No longer need to enable writing stats
